### ISSUE TITLE
high-level plot outline

### ISSUE THREAD

**Issue by jackmakesthings** [jackmakesthings/game-dev#110]
Based on the plot as it currently exists, we need a document outlining key decision points, events, etc, in sequence from the start to end of the game. Doesn't need to be super detailed, but shouldn't have any major gaps. Should note changes to the states of major characters at any given point (ie, if anyone shows up, leaves, or changes in some significant way, that should be kept track of as part of this doc).

(Please attach a link to the doc to this ticket when you're ready to share it)

**Comment by Batbro** [comment]
Complete story map located [here.](https://drive.google.com/file/d/0B1hW4M_pvanAM3g2OVNBbklmMGM/view?usp=sharing)
