### ISSUE TITLE
panels: prototype adjacent-space transitions

### ISSUE THREAD

**Issue by jackmakesthings** [jackmakesthings/game-dev#121]
Goal is to set up a working demo of a multi-panel space where the adjacent spaces are continuous - IE, a large room (rather than two rooms with a door between them).

**Comment by jackmakesthings** [comment]
@Batbro assigning this to you, I'll take it back once you've made an animatic rendering for this.

**Comment by Batbro** [comment]
I think it's best I keep these simple and demonstrate single concepts at a time.  This is an example of moving around a room too large to fit entirely on the screen at once.  The behaviors would operate similarly for any movement along the Y axis.

[LINK](https://drive.google.com/open?id=0B1hW4M_pvanAWnBXeEM1Q2ZyaW8)

**Comment by jackmakesthings** [comment]
@Batbro check it out, I have a working follow-camera that basically matches your design. I'm starting to prototype non-tile-based, non-isometric areas, using our existing player assets and some placeholder backgrounds. I didn't rig up an indicator to show when I click, but you can probably infer based on the player movement.

![3obyfgcskx](https://cloud.githubusercontent.com/assets/3606708/20725769/ec995540-b640-11e6-99ab-4eb7e0d85cb7.gif)


We can set limits on the camera to create the "ends" of the area - in this demo there's a limit set on the left edge, so no matter how far to the left we walk, we won't see the blank space to the left of the background image. In practice, we'll set one on the other edges as well.

We can also control things like how sensitive it is to motion (ie how far you have to be off-center for the camera to start moving), as well as "smoothing" (see how the camera sort of slides to catch up with the player after they stop? that can be configured or disabled.) The Godot 2d camera is pretty robust.

**Comment by Batbro** [comment]
This looks like everything I dreamed and more. The camera smoothing and
off-center allowance are features I definitely considered "optional, but
fantastic if possible."

The off-center allowance I see being useful for like, "I clicked to move
near a thing and now I want to interact with it." Now Trace can finish
closing that distance without the camera moving again.

**Comment by Batbro** [comment]
Also I'm feeling rather productive and have a lot of free time tomorrow.
Gimme a list of any additional animatics you'd like. Camera movements, UI
stuff, whatever.
