### ISSUE TITLE
panels: prototype door-style transitions

### ISSUE THREAD

**Issue by jackmakesthings** [jackmakesthings/game-dev#122]
Related to the previous ticket - this is for a working demo of room-changing behavior with a transition in between. Moving between distinct areas or rooms.

**Comment by jackmakesthings** [comment]
@Batbro can you attach that swf animatic you made to this issue? (You can attach files to comments.)

**Comment by Batbro** [comment]
Github does not support uploading swf files, but here's [a link](https://drive.google.com/open?id=0B1hW4M_pvanAdTFHaWtqZ3prN1E) to the file on my drive.
