### ISSUE TITLE
define skill/upgrade system

### ISSUE THREAD

**Issue by jackmakesthings** [jackmakesthings/game-dev#39]
need to map out a general structure for "resource upgrades" - currently envisioned as a node graph or tree.

**Comment by Batbro** [comment]
[Upgrade Tree/Sample Builds](https://docs.google.com/spreadsheets/d/1YidU4yDsVUlrmMl_qNTljxZGKeqGuAkRzgN4YLN5Vu4/edit?usp=sharing)
